server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost/francesinha_users?useSSL=false
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter: DEBUG
    shop.francesinha.products: INFO
    org.hibernate: ERROR