server:
  port: 8080
spring:
  datasource:
    hikari:
      initialization-fail-timeout: 60000
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 1
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/francesinha_users?useSSL=false
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter: DEBUG
    shop.francesinha.products: INFO
    org.hibernate: ERROR
management:
  endpoints:
    web:
      exposure:
        include: health