spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      max-lifetime: 18000  # shorter than MySQL timeout
      connection-timeout: 30000
logging:
  level:
    shop.francesinha.backend: DEBUG
    org.hibernate: ERROR