services:
  mysql:
    image: mysql:8.1
    container_name: mysql
    volumes:
      - ./databases_init.sql:/docker-entrypoint-initdb.d/databases_init.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 5s
      retries: 50

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: francesinha_reviews
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 20s
      timeout: 5s
      retries: 50

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.7.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"  # internal listener for brokers
      - "9093:9093"  # external listener for host access
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Map listener names to protocols
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      # Distinct ports for each listener
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      # Tell Kafka which listener brokers use for inter-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  auth:
    working_dir: /app
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 50
      start_period: 20s
    depends_on:
      mysql:
        condition: service_healthy

  products:
    working_dir: /app
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      AUTH_HOST: auth
    ports:
      - "8081:8081"
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 50
    depends_on:
      mysql:
        condition: service_healthy

  reviews:
    working_dir: /app
    environment:
      AUTH_HOST: auth
      MONGO_HOST: mongodb
      MONGO_USER: root
      MONGO_PASSWORD: example
      PRODUCT_ENDPOINT: http://products:8081
    ports:
      - "8082:8082"
    healthcheck:
      test: "curl --fail --silent localhost:8082/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 50
    depends_on:
      mongodb:
        condition: service_healthy