version: "3.9"

services:
  auth:
    image: openjdk:24
    working_dir: /app
    volumes:
      - ../services-auth:/app
    command: mvn spring-boot:run
    ports:
      - "8080:8080"

  products:
    image: openjdk:24
    working_dir: /app
    volumes:
      - ../services-products:/app
    command: mvn spring-boot:run
    ports:
      - "8081:8081"

  reviews:
    image: openjdk:24
    working_dir: /app
    volumes:
      - ../services-reviews:/app
    command: mvn spring-boot:run
    ports:
      - "8082:8082"
    depends_on:
      - auth
      - products

  e2e-tests:
    build: .
    command: mvn verify -Pe2e
    depends_on:
      - auth
      - products
      - reviews
