version: "3.9"

services:
  mysql:
    image: mysql:8.1
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: francesinha
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  auth:
    image: maven:3.9.9-eclipse-temurin-24
    working_dir: /app
    volumes:
      - ../services-auth:/app
    command: mvn spring-boot:run "-Dspring-boot.run.profiles=test"
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  products:
    image: maven:3.9.9-eclipse-temurin-24
    working_dir: /app
    volumes:
      - ../services-products:/app
    command: mvn spring-boot:run "-Dspring-boot.run.profiles=test"
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  reviews:
    image: maven:3.9.9-eclipse-temurin-24
    working_dir: /app
    volumes:
      - ../services-reviews:/app
    command: mvn spring-boot:run "-Dspring-boot.run.profiles=test"
    ports:
      - "8082:8082"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      auth:
        condition: service_healthy
      products:
        condition: service_healthy

  e2e-tests:
    build: .
    command: mvn verify
    depends_on:
      mysql:
        condition: service_healthy
      auth:
        condition: service_healthy
      products:
        condition: service_healthy
      reviews:
        condition: service_healthy