version: "3.9"

services:
  auth:
    image: maven:3.9.9-eclipse-temurin-24
    working_dir: /app
    volumes:
      - ../services-auth:/app
    command: mvn spring-boot:run "-Dspring-boot.run.profiles=test"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  products:
    image: maven:3.9.9-eclipse-temurin-24
    working_dir: /app
    volumes:
      - ../services-products:/app
    command: mvn spring-boot:run "-Dspring-boot.run.profiles=test"
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  reviews:
    image: maven:3.9.9-eclipse-temurin-24
    working_dir: /app
    volumes:
      - ../services-reviews:/app
    command: mvn spring-boot:run "-Dspring-boot.run.profiles=test"
    ports:
      - "8082:8082"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      auth:
        condition: service_healthy
      products:
        condition: service_healthy

  e2e-tests:
    build: .
    command: mvn verify
    depends_on:
      auth:
        condition: service_healthy
      products:
        condition: service_healthy
      reviews:
        condition: service_healthy