version: "3.9"

services:
  auth:
    build: ../services-auth
    command: mvn spring-boot:run
    ports:
      - "8080:8080"

  products:
    build: ../services-products
    command: mvn spring-boot:run
    ports:
      - "8081:8081"

  reviews:
    build: ../services-reviews
    command: mvn spring-boot:run
    ports:
      - "8082:8082"
    depends_on:
      - auth
      - products

  e2e-tests:
    build: .
    command: mvn verify -Pe2e
    depends_on:
      - auth
      - products
      - reviews
