server:
  port: 8082
spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:27017/francesinha_reviews
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${AUTH_HOST:localhost}:8080/auth/.well-known/jwks.json
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter: DEBUG
    shop.francesinha.products: INFO
    org.hibernate: ERROR
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always