server:
  port: 8082
spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:27017/francesinha_reviews
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${AUTH_HOST:localhost}:8080/auth/.well-known/jwks.json
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: reviews-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter: DEBUG
    org.springframework.boot.actuate.endpoint.web.servlet: WARN
    shop.francesinha.products: INFO
    org.hibernate: ERROR
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always