name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      # 3️⃣ Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4️⃣ Build and run tests
      - name: Build and run tests with coverage
        run: mvn clean verify -B

      # 5️⃣ Upload JaCoCo HTML report (optional)
      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco-merged/

      # 6️⃣ Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: target/site/jacoco-merged/jacoco.xml
          fail_ci_if_error: false
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

      # 7️⃣ Warn if coverage < 75% (optional)
      - name: Check coverage
        run: |
          # Extract the first line-rate value using awk (no -P needed)
          COVERAGE=$(grep 'line-rate=' target/site/jacoco-merged/jacoco.xml | head -1 | awk -F '"' '{print $2}')
          if [ -z "$COVERAGE" ]; then
            echo "❌ Coverage value not found. Ensure 'mvn verify jacoco:report' ran successfully."
            exit 0    # Don't fail the build, just warn
          fi
          PERCENT=$(awk "BEGIN {print $COVERAGE * 100}")
          echo "Line coverage: $PERCENT%"
          if (( $(echo "$PERCENT < 75" | bc -l) )); then
            echo "⚠️ Warning: Coverage is below 75%"
          fi